"""Initial migration

Revision ID: 4f138aea945b
Revises: 
Create Date: 2025-08-07 15:57:25.710244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f138aea945b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('account_list',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('is_welcome_bonus', sa.Boolean(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_list_login'), ['login'], unique=True)

    op.create_table('crm_deposit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.Column('trading_account', sa.String(length=50), nullable=True),
    sa.Column('trading_amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_deposit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_deposit_request_id'), ['request_id'], unique=True)

    op.create_table('crm_withdrawals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('review_time', sa.DateTime(), nullable=True),
    sa.Column('trading_account', sa.String(length=50), nullable=True),
    sa.Column('withdrawal_amount', sa.Float(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_withdrawals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_withdrawals_request_id'), ['request_id'], unique=True)

    op.create_table('ib_rebate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('rebate', sa.Float(), nullable=True),
    sa.Column('rebate_time', sa.DateTime(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ib_rebate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ib_rebate_transaction_id'), ['transaction_id'], unique=True)

    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=True),
    sa.Column('details', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('payment_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.String(length=20), nullable=True),
    sa.Column('tx_id', sa.String(length=100), nullable=True),
    sa.Column('wallet_address', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('payment_gateway', sa.String(length=100), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('final_currency', sa.String(length=10), nullable=True),
    sa.Column('settlement_amount', sa.Float(), nullable=True),
    sa.Column('settlement_currency', sa.String(length=10), nullable=True),
    sa.Column('processing_fee', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('trading_account', sa.String(length=50), nullable=True),
    sa.Column('correct_coin_sent', sa.Boolean(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('tier_fee', sa.Float(), nullable=True),
    sa.Column('sheet_category', sa.String(length=50), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_data_tx_id'), ['tx_id'], unique=True)

    op.create_table('uploaded_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_files')
    with op.batch_alter_table('payment_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_data_tx_id'))

    op.drop_table('payment_data')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_timestamp'))

    op.drop_table('logs')
    with op.batch_alter_table('ib_rebate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ib_rebate_transaction_id'))

    op.drop_table('ib_rebate')
    with op.batch_alter_table('crm_withdrawals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_withdrawals_request_id'))

    op.drop_table('crm_withdrawals')
    with op.batch_alter_table('crm_deposit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_deposit_request_id'))

    op.drop_table('crm_deposit')
    with op.batch_alter_table('account_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_list_login'))

    op.drop_table('account_list')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
